name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: tabithamoon
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: tabithamoon/tabbynet
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
